export const ActionType = {
  SET_LOAN_AMOUNT: 'SET_LOAN_AMOUNT',
  SET_BORROWING_RATE: 'SET_BORROWING_RATE',
  SET_REPAYMENT_RATE: 'SET_REPAYMENT_RATE',
  SET_FIXED_INTEREST_PERIOD_IN_YEARS: 'SET_FIXED_INTEREST_PERIOD_IN_YEARS',
  SET_INSTALLMENT_TYPE: 'SET_INSTALLMENT_TYPE',
  SET_PAYOUT_DATE: 'SET_PAYOUT_DATE',
} as const;
